import os
from typing import final

def execution_capabilities() -> dict[str, object]:
    """Execution mode, background/live-event/cancel flags, and worker limit."""
    ...

def entry_domain_plan(source: str) -> dict[str, object]:
    """Count/preview a finite input envelope; does not solve or certify it."""
    ...

class RustRedError(Exception): ...
class RustRedInputError(RustRedError): ...
class RustRedSchemaError(RustRedInputError): ...
class RustRedLimitError(RustRedInputError): ...
class RustRedLoweringError(RustRedInputError): ...
class RustRedDerivationError(RustRedError): ...
class RustRedExecutionError(RustRedError): ...
class RustRedLicenseError(RustRedExecutionError): ...
class RustRedSerializationError(RustRedError): ...
class RustRedOutputLimitError(RustRedSerializationError): ...
class RustRedInternalError(RustRedError): ...
class RustRedCoordinatorPoisonedError(RustRedInternalError): ...

@final
class CandidateBundleResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def bundle(self) -> bytes: ...
    def to_toml(self) -> str: ...
    def artifact(self) -> CandidateArtifact: ...

@final
class CandidateGenerationRequest:
    def start(self, *, event_capacity: int = 256) -> CandidateGenerationSession: ...

@final
class CandidateGenerationSession:
    @property
    def execution_mode(self) -> str: ...
    def _repr_html_(self) -> str: ...
    @property
    def done(self) -> bool: ...
    def cancel(self) -> None: ...
    def snapshot(self) -> dict[str, object]: ...
    def poll_events(self, max_events: int = 128, timeout: float = 0.0) -> dict[str, object]: ...
    def wait(self, timeout: float | None = None) -> bool: ...
    def result(self) -> CandidateBundleResult: ...

@final
class CandidateArtifact:
    def _repr_html_(self) -> str: ...
    @staticmethod
    def open(bundle: bytes, *, bundle_max_bytes: int | None = None, bundle_max_entries: int | None = None, bundle_max_coefficient_bytes: int | None = None, bundle_max_total_coefficient_bytes: int | None = None) -> CandidateArtifact: ...
    @staticmethod
    def open_file(path: str | os.PathLike[str], *, bundle_max_bytes: int | None = None, bundle_max_entries: int | None = None, bundle_max_coefficient_bytes: int | None = None, bundle_max_total_coefficient_bytes: int | None = None) -> CandidateArtifact: ...
    def metadata(self) -> dict[str, object]: ...
    def sectors(self, start: int = 0, limit: int = 50) -> dict[str, object]: ...
    def rules(self, sector: int, start: int = 0, limit: int = 50) -> dict[str, object]: ...
    def terminals(self, sector: int, start: int = 0, limit: int = 50) -> dict[str, object]: ...
    def rule(self, sector: int, ordinal: int, *, max_output_bytes: int = 1048576) -> dict[str, object]: ...
    def coefficient(self, id: int, *, max_output_bytes: int = 65536) -> dict[str, object]: ...

@final
class TerminalNormalization:
    """Exact finite within-family identities, not a minimal master basis or closure proof."""
    def _repr_html_(self) -> str: ...
    def metadata(self) -> dict[str, object]: ...
    def terminals(self, start: int = 0, limit: int = 50) -> dict[str, object]: ...
    def relations(self, start: int = 0, limit: int = 50) -> dict[str, object]: ...
    def relation(self, ordinal: int, *, max_output_bytes: int = 1048576) -> dict[str, object]: ...
    def coefficient(self, id: int, *, max_output_bytes: int = 65536) -> dict[str, object]: ...
    def sidecar(self) -> bytes: ...

def candidate_generation_request(source: str, **options: object) -> CandidateGenerationRequest: ...
def start_family_candidates(source: str, *, event_capacity: int = 256, **options: object) -> CandidateGenerationSession: ...

@final
class DeriveResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_toml(self) -> str: ...

@final
class CampaignPlanResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_toml(self) -> str: ...

@final
class CampaignPreflightResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_toml(self) -> str: ...

@final
class FoundryCampaignRunResult:
    @property
    def schema(self) -> str: ...
    @property
    def measurements_schema(self) -> str: ...
    def to_toml(self) -> str: ...
    def measurements_to_toml(self) -> str: ...

@final
class FoundryWaveCampaignRunResult:
    @property
    def schema(self) -> str: ...
    @property
    def measurements_schema(self) -> str: ...
    @property
    def artifact_bytes(self) -> bytes | None: ...
    def to_toml(self) -> str: ...
    def measurements_to_toml(self) -> str: ...

@final
class ClosingArtifactGenerationResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def artifact(self) -> bytes: ...
    def to_toml(self) -> str: ...

@final
class ClosingArtifactInspectionResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_toml(self) -> str: ...

@final
class ExactMasterCoefficient:
    @property
    def master_powers(self) -> list[int]: ...
    @property
    def unit_mass_coefficient(self) -> str: ...
    @property
    def common_mass_squared_power(self) -> int: ...

@final
class ClosingArtifactReductionResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def family_fingerprint(self) -> str: ...
    @property
    def target_powers(self) -> list[int]: ...
    @property
    def terms(self) -> list[ExactMasterCoefficient]: ...
    def to_toml(self) -> str: ...

__version__: str

def derive(
    source: str,
    *,
    input_format: str = "auto",
    relations: str = "all",
    n_cores: int = 1,
) -> DeriveResult: ...

def campaign_plan(
    source: str,
    *,
    input_format: str = "auto",
    root_id: str | None = None,
) -> CampaignPlanResult: ...

def campaign_preflight(
    profile: str,
    *,
    n_cores: int = 1,
    max_memory_bytes: int,
) -> CampaignPreflightResult: ...

def run_foundry_campaign(
    config: str,
) -> FoundryCampaignRunResult: ...

def run_foundry_wave_campaign(
    config: str,
    *,
    n_cores: int = 1,
) -> FoundryWaveCampaignRunResult: ...

def generate_closing_artifact(
    *,
    family: str = "unit-mass-vacuum-k1",
) -> ClosingArtifactGenerationResult: ...

def family_close(
    source: str,
    *,
    input_format: str = "auto",
    n_cores: int = 1,
    permutation: list[int] | None = None,
    nonpositive_indices: list[int] | None = None,
    max_domain_bound_endpoint_cells: int | None = None,
    max_predicate_consistency_work: int | None = None,
    max_predicate_atoms: int | None = None,
) -> ClosingArtifactGenerationResult: ...

def family_candidates(
    source: str,
    *,
    input_format: str = "auto",
    n_cores: int = 1,
    permutation: list[int] | None = None,
    nonpositive_indices: list[int] | None = None,
    exact_backend: str = "sparse",  # sparse, sparse-factorized, sparse-target-factorized, semi-numerical
    numerical_depth: int = 2,
    max_numerator_rank: int | None = None,
    finite_case_policy: str = "search",
    finite_max_visited_points: int | None = None,
    finite_max_retained_terminals: int | None = None,
    case_max_work_items: int | None = None,
    case_max_terms_per_conjunction: int | None = None,
    case_max_normalizations: int | None = None,
    case_max_factorizations: int | None = None,
    bundle_max_bytes: int | None = None,
    bundle_max_entries: int | None = None,
    bundle_max_coefficient_bytes: int | None = None,
    bundle_max_total_coefficient_bytes: int | None = None,
    checkpoint_dir: str | os.PathLike[str] | None = None,
    resume: bool = False,
    checkpoint_max_bytes: int | None = None,
    discovery_strategy: str | None = None,
    integral_order: str | None = None,
    selected_sectors: list[str] | None = None,
) -> CandidateBundleResult: ...

def inspect_candidate_program(bundle: bytes, *, options_json: str | None = None) -> str:
    """Native read-only diagnostic JSON; not an artifact or proof."""
    ...

def certify_candidates(
    bundle: bytes,
    *,
    max_domain_bound_endpoint_cells: int | None = None,
    max_predicate_consistency_work: int | None = None,
    max_predicate_atoms: int | None = None,
    max_negative_index_degree: int | None = None,
    max_total_excess_degree: int | None = None,
) -> ClosingArtifactGenerationResult: ...

def inspect_closing_artifact(
    artifact: bytes,
    *,
    max_domain_bound_endpoint_cells: int | None = None,
    max_predicate_consistency_work: int | None = None,
    max_predicate_atoms: int | None = None,
) -> ClosingArtifactInspectionResult: ...

def reduce_with_closing_artifact(
    artifact: bytes,
    target_powers: list[int],
    *,
    max_rule_applications: int = 1_000_000,
    max_domain_bound_endpoint_cells: int | None = None,
    max_predicate_consistency_work: int | None = None,
    max_predicate_atoms: int | None = None,
) -> ClosingArtifactReductionResult: ...
