from typing import final

class RustRedError(Exception): ...
class RustRedInputError(RustRedError): ...
class RustRedSchemaError(RustRedInputError): ...
class RustRedLimitError(RustRedInputError): ...
class RustRedLoweringError(RustRedInputError): ...
class RustRedDerivationError(RustRedError): ...
class RustRedExecutionError(RustRedError): ...
class RustRedLicenseError(RustRedExecutionError): ...
class RustRedSerializationError(RustRedError): ...
class RustRedOutputLimitError(RustRedSerializationError): ...
class RustRedInternalError(RustRedError): ...
class RustRedCoordinatorPoisonedError(RustRedInternalError): ...

@final
class DeriveResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_toml(self) -> str: ...

@final
class CampaignPlanResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_toml(self) -> str: ...

@final
class CampaignPreflightResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_toml(self) -> str: ...

__version__: str

def derive(
    source: str,
    *,
    input_format: str = "auto",
    relations: str = "all",
    n_cores: int = 1,
) -> DeriveResult: ...

def campaign_plan(
    source: str,
    *,
    input_format: str = "auto",
    root_id: str | None = None,
) -> CampaignPlanResult: ...

def campaign_preflight(
    profile: str,
    *,
    n_cores: int = 1,
    max_memory_bytes: int,
) -> CampaignPreflightResult: ...
