from typing import final

class RustRedError(Exception): ...
class RustRedInputError(RustRedError): ...
class RustRedSchemaError(RustRedInputError): ...
class RustRedLimitError(RustRedInputError): ...
class RustRedLoweringError(RustRedInputError): ...
class RustRedDerivationError(RustRedError): ...
class RustRedExecutionError(RustRedError): ...
class RustRedLicenseError(RustRedExecutionError): ...
class RustRedSerializationError(RustRedError): ...
class RustRedOutputLimitError(RustRedSerializationError): ...
class RustRedInternalError(RustRedError): ...
class RustRedCoordinatorPoisonedError(RustRedInternalError): ...

@final
class DeriveResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_toml(self) -> str: ...

@final
class CampaignPlanResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_toml(self) -> str: ...

@final
class CampaignPreflightResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_toml(self) -> str: ...

@final
class FoundryCampaignRunResult:
    @property
    def schema(self) -> str: ...
    @property
    def measurements_schema(self) -> str: ...
    def to_toml(self) -> str: ...
    def measurements_to_toml(self) -> str: ...

@final
class FoundryWaveCampaignRunResult:
    @property
    def schema(self) -> str: ...
    @property
    def measurements_schema(self) -> str: ...
    def to_toml(self) -> str: ...
    def measurements_to_toml(self) -> str: ...

@final
class ClosingArtifactGenerationResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def artifact(self) -> bytes: ...
    def to_toml(self) -> str: ...

@final
class ClosingArtifactInspectionResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    def to_toml(self) -> str: ...

@final
class ExactMasterCoefficient:
    @property
    def master_powers(self) -> list[int]: ...
    @property
    def unit_mass_coefficient(self) -> str: ...
    @property
    def common_mass_squared_power(self) -> int: ...

@final
class ClosingArtifactReductionResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def family_fingerprint(self) -> str: ...
    @property
    def target_powers(self) -> list[int]: ...
    @property
    def terms(self) -> list[ExactMasterCoefficient]: ...
    def to_toml(self) -> str: ...

__version__: str

def derive(
    source: str,
    *,
    input_format: str = "auto",
    relations: str = "all",
    n_cores: int = 1,
) -> DeriveResult: ...

def campaign_plan(
    source: str,
    *,
    input_format: str = "auto",
    root_id: str | None = None,
) -> CampaignPlanResult: ...

def campaign_preflight(
    profile: str,
    *,
    n_cores: int = 1,
    max_memory_bytes: int,
) -> CampaignPreflightResult: ...

def run_foundry_campaign(
    config: str,
) -> FoundryCampaignRunResult: ...

def run_foundry_wave_campaign(
    config: str,
    *,
    n_cores: int = 1,
) -> FoundryWaveCampaignRunResult: ...

def generate_closing_artifact(
    *,
    family: str = "unit-mass-vacuum-k1",
) -> ClosingArtifactGenerationResult: ...

def inspect_closing_artifact(
    artifact: bytes,
) -> ClosingArtifactInspectionResult: ...

def reduce_with_closing_artifact(
    artifact: bytes,
    target_powers: list[int],
    *,
    max_rule_applications: int = 1_000_000,
) -> ClosingArtifactReductionResult: ...
