//! Built-in integral families used by validation milestones.

use rustred::{CoefficientContext, Denominator, ExactRational, FamilyError, VacuumFamily};

/// The equal-mass two-loop sunset family
///
/// ```text
/// D1 = k1^2 + m2
/// D2 = k2^2 + m2
/// D3 = (k1 + k2)^2 + m2
/// ```
///
/// The plus sign is the Euclidean convention.  The full `S3` denominator
/// symmetry is generated by a transposition and a 3-cycle.
pub fn equal_mass_two_loop_vacuum() -> Result<VacuumFamily, FamilyError> {
    equal_mass_two_loop_vacuum_in_context(CoefficientContext::new(["d", "m2"]))
}

/// Construct the standard equal-mass sunset in a caller-supplied coefficient
/// context.
///
/// Factorized higher-loop reductions use this surface so the induced sunset
/// and the parent integral share the exact Symbolica variable map.  The
/// context must define both `d` and `m2`; [`VacuumFamily::new`] validates `d`
/// as the dimension parameter, while the explicit lookup below validates the
/// common mass.
pub fn equal_mass_two_loop_vacuum_in_context(
    coefficients: CoefficientContext,
) -> Result<VacuumFamily, FamilyError> {
    equal_mass_two_loop_vacuum_with_reversed_denominators(coefficients, false)
}

/// The equal-mass two-loop sunset family with every denominator reversed:
///
/// ```text
/// D1 = -(k1^2 + m2)
/// D2 = -(k2^2 + m2)
/// D3 = -((k1 + k2)^2 + m2)
/// ```
///
/// This is an exact sign-convention counterpart of
/// [`equal_mass_two_loop_vacuum`], useful when importing families whose
/// propagators are defined with the opposite overall sign.
pub fn equal_mass_two_loop_vacuum_reversed() -> Result<VacuumFamily, FamilyError> {
    equal_mass_two_loop_vacuum_with_reversed_denominators(
        CoefficientContext::new(["d", "m2"]),
        true,
    )
}

fn equal_mass_two_loop_vacuum_with_reversed_denominators(
    coefficients: CoefficientContext,
    reversed: bool,
) -> Result<VacuumFamily, FamilyError> {
    let mass = coefficients
        .parameter("m2")
        .ok_or_else(|| FamilyError::UnknownCoefficientParameter("m2".to_owned()))?;
    let momentum =
        |left: i64, right: i64| vec![ExactRational::from(left), ExactRational::from(right)];
    let denominator = |routing, shift| {
        if reversed {
            Denominator::reversed_propagator(routing, shift)
        } else {
            Denominator::propagator(routing, shift)
        }
    };
    let denominators = vec![
        denominator(momentum(1, 0), mass.clone()),
        denominator(momentum(0, 1), mass.clone()),
        denominator(momentum(1, 1), mass),
    ];

    VacuumFamily::new(
        if reversed {
            "equal_mass_two_loop_vacuum_reversed"
        } else {
            "equal_mass_two_loop_vacuum"
        },
        2,
        coefficients,
        "d",
        denominators,
        vec![vec![1, 0, 2], vec![1, 2, 0]],
    )
}
