//! Direct-concrete oracle for generated connected two-loop sunset IBPs.
//!
//! The only concrete object here is the test fixture. Every source row is
//! generated by the topology-generic parametric IBP generator; no recurrence,
//! FORM program, or Mathematica output is embedded in this test.

use std::sync::Arc;

use rustred::{
    AffineDenominator, AffineLocusBoundRelationCompilation, AffineLocusBoundRelationCompiler,
    AffineLocusBoundRelationLimits, AffineLocusConcreteSpecializationLimits, CoefficientContext,
    CoordinateEqualityLocusCertificate, CoordinateEqualityLocusExtractor,
    CoordinateEqualityLocusLimits, IndexShift, IntegralFamily, ParametricCoefficientContext,
    ParametricIbpGenerator, ParametricRelation, ParametricRowId,
    ResidualUnitAffineIndexMapCertificate, ResidualUnitAffineIndexMapLimits, SectorMask,
    SymbolicPolynomialPredicateKind, SymbolicSectorCaseLimits, SymbolicSectorCasePartitionBuilder,
};

fn equal_mass_sunset() -> IntegralFamily {
    let coefficients = CoefficientContext::new(["d", "m2"]);
    let zero = coefficients.zero();
    let one = coefficients.one();
    let minus_m2 = coefficients.parse("-m2").unwrap();
    IntegralFamily::new(
        "affine-locus-generated-sunset-oracle",
        vec!["k1".into(), "k2".into()],
        Vec::new(),
        coefficients.clone(),
        coefficients.parameter("d").unwrap(),
        vec![
            AffineDenominator::new(
                minus_m2.clone(),
                vec![one.clone(), zero.clone(), zero.clone()],
            ),
            AffineDenominator::new(
                minus_m2.clone(),
                vec![zero.clone(), zero.clone(), one.clone()],
            ),
            AffineDenominator::new(minus_m2, vec![one.clone(), coefficients.integer(2), one]),
        ],
        Vec::new(),
        vec![zero.clone(), zero.clone(), zero],
    )
    .unwrap()
}

fn affine_map(
    context: &ParametricCoefficientContext,
) -> Arc<ResidualUnitAffineIndexMapCertificate> {
    let sum = context
        .add(&context.index(0).unwrap(), &context.index(1).unwrap())
        .unwrap();
    let affine = context.sub(&sum, &context.integer(3)).unwrap();
    let d = context
        .lift(&context.base().parameter("d").unwrap())
        .unwrap();
    let base_factor = context.add(&d, &context.one()).unwrap();
    let predicate = context.mul(&base_factor, &affine).unwrap();

    let mut builder = SymbolicSectorCasePartitionBuilder::try_new(
        context,
        SectorMask::try_new([true, true, true]).unwrap(),
        SymbolicSectorCaseLimits::default(),
    )
    .unwrap();
    let leaf = builder
        .split_on_bad_polynomial(
            context,
            builder.root_case(),
            context.numerator_condition(&predicate).unwrap(),
        )
        .unwrap()
        .equal_zero_case();
    let partition = builder.finish(context).unwrap();
    let source = Arc::new(
        CoordinateEqualityLocusExtractor::extract(
            context,
            &partition,
            leaf,
            CoordinateEqualityLocusLimits::default(),
        )
        .unwrap(),
    );
    let predicate_ordinal = dependent_equality_ordinal(&source);
    Arc::new(
        ResidualUnitAffineIndexMapCertificate::compile(
            context,
            source,
            predicate_ordinal,
            0,
            ResidualUnitAffineIndexMapLimits::default(),
        )
        .unwrap(),
    )
}

fn dependent_equality_ordinal(source: &CoordinateEqualityLocusCertificate) -> usize {
    source
        .unresolved_predicates()
        .iter()
        .find(|predicate| predicate.kind() == SymbolicPolynomialPredicateKind::EqualZero)
        .unwrap()
        .predicate_ordinal()
}

fn polynomial_multiset(relation: &rustred::ConcreteRelation) -> Vec<String> {
    let mut polynomials = relation
        .nonzero_conditions()
        .iter()
        .map(|polynomial| polynomial.raw().to_string())
        .collect::<Vec<_>>();
    polynomials.sort();
    polynomials
}

#[test]
fn every_generated_sunset_ibp_agrees_with_direct_concrete_specialization() {
    let family = equal_mass_sunset();
    let generated = ParametricIbpGenerator::try_new(&family)
        .unwrap()
        .generate()
        .unwrap();
    assert_eq!(generated.ordinary_ibp().len(), 4);
    let context = generated.context();
    let map = affine_map(context);
    assert_eq!(map.free_positions(), &[1, 2]);

    let displacements = [[0, 0, 0], [1, 0, 0], [0, -1, 1], [-1, 1, 0], [2, -1, 0]];
    let free_points = [[1, 1], [2, 1], [1, 2], [2, 2]];

    for (row_ordinal, source) in generated.ordinary_ibp().iter().enumerate() {
        for (displacement_ordinal, displacement) in displacements.iter().enumerate() {
            let translation = IndexShift::try_new(*displacement, 3).unwrap();
            let target_row_id = ParametricRowId::Derived {
                label: Arc::from(format!(
                    "sunset-affine-oracle-{row_ordinal}-{displacement_ordinal}"
                )),
            };
            let compilation = AffineLocusBoundRelationCompiler::compile(
                context,
                Arc::new(source.clone()),
                translation,
                target_row_id,
                map.clone(),
                AffineLocusBoundRelationLimits::default(),
            )
            .unwrap();
            let AffineLocusBoundRelationCompilation::Retained(bound) = compilation else {
                panic!(
                    "generated sunset row {row_ordinal}, displacement {displacement_ordinal} unexpectedly became unavailable"
                );
            };
            bound.replay(context).unwrap();

            for [t, u] in free_points {
                let ambient = [3 - t, t, u];
                let direct_point = [
                    ambient[0] + displacement[0],
                    ambient[1] + displacement[1],
                    ambient[2] + displacement[2],
                ];
                let affine = bound
                    .specialize_at_free_values(
                        context,
                        &[t, u],
                        AffineLocusConcreteSpecializationLimits::default(),
                    )
                    .unwrap();
                let direct = source
                    .specialize(
                        context,
                        &direct_point,
                        AffineLocusConcreteSpecializationLimits::default().arithmetic,
                    )
                    .unwrap();
                assert_eq!(affine.family_fingerprint(), direct.family_fingerprint());
                assert_eq!(
                    affine.terms(),
                    direct.terms(),
                    "term mismatch for row {row_ordinal}, displacement {displacement:?}, free point ({t},{u})"
                );
                assert_eq!(
                    polynomial_multiset(&affine),
                    polynomial_multiset(&direct),
                    "guard mismatch for row {row_ordinal}, displacement {displacement:?}, free point ({t},{u})"
                );
            }
        }
    }
}

#[test]
fn guarded_rational_multiple_of_a_generated_sunset_ibp_preserves_its_mapped_domain() {
    let family = equal_mass_sunset();
    let generated = ParametricIbpGenerator::try_new(&family)
        .unwrap()
        .generate()
        .unwrap();
    let context = generated.context();
    let genuine_generated_row = &generated.ordinary_ibp()[0];
    let d = context
        .lift(&context.base().parameter("d").unwrap())
        .unwrap();
    let denominator = context
        .sub(
            &context
                .add(
                    &context.add(&d, &context.index(0).unwrap()).unwrap(),
                    &context.index(2).unwrap(),
                )
                .unwrap(),
            &context.integer(2),
        )
        .unwrap();
    let guarded_factor = context.checked_div(&context.one(), &denominator).unwrap();
    let mut source = ParametricRelation::new(
        genuine_generated_row.family_fingerprint(),
        ParametricRowId::Derived {
            label: Arc::from("guarded-rational-generated-sunset-row"),
        },
        context,
    );
    source
        .add_scaled(context, genuine_generated_row, &guarded_factor)
        .unwrap();
    let source = Arc::new(source);
    let map = affine_map(context);
    let AffineLocusBoundRelationCompilation::Retained(bound) =
        AffineLocusBoundRelationCompiler::compile(
            context,
            source.clone(),
            IndexShift::try_new([0, 0, 0], 3).unwrap(),
            ParametricRowId::Derived {
                label: Arc::from("guarded-rational-generated-sunset-affine"),
            },
            map,
            AffineLocusBoundRelationLimits::default(),
        )
        .unwrap()
    else {
        panic!("the guarded generated row must be available on this affine locus");
    };
    assert!(bound.stats().durable_guard_terms() > 0);
    bound.replay(context).unwrap();

    for [t, u] in [[1, 1], [2, 1], [1, 2], [2, 2]] {
        let ambient = [3 - t, t, u];
        let affine = bound
            .specialize_at_free_values(
                context,
                &[t, u],
                AffineLocusConcreteSpecializationLimits::default(),
            )
            .unwrap();
        let direct = source
            .specialize(
                context,
                &ambient,
                AffineLocusConcreteSpecializationLimits::default().arithmetic,
            )
            .unwrap();
        assert_eq!(affine.family_fingerprint(), direct.family_fingerprint());
        assert_eq!(affine.terms(), direct.terms());
        assert_eq!(polynomial_multiset(&affine), polynomial_multiset(&direct));
        assert!(!polynomial_multiset(&affine).is_empty());
    }
}
