//! One-loop boundary and adversarial checks for generated conditional
//! re-elimination.  The fixture supplies only a family and equality locus;
//! every equation is freshly generated by RustRed.

use rustred::{
    AffineDenominator, CoefficientContext, CoefficientLocation,
    GENERATED_PARTIAL_REELIMINATION_V2_SCHEMA, GeneratedPartialReeliminationCompilation,
    GeneratedPartialReeliminationCompiler, GeneratedPartialReeliminationError,
    GeneratedPartialReeliminationLimits, GeneratedPartialSourceAuthentication,
    GeneratedPartialSourceRowOutcome, GuardOrigin, IndexSpace, IntegralFamily,
    IntegralOrderingPolicy, ParametricCoefficientContext, ParametricEliminationOrdering,
    ParametricIbpGenerator, ParametricRowId, PartialIndexAssignment,
};

fn one_loop_family(name: &str) -> IntegralFamily {
    let coefficients = CoefficientContext::new(["d", "m2"]);
    IntegralFamily::new(
        name,
        vec!["k".into()],
        Vec::new(),
        coefficients.clone(),
        coefficients.parameter("d").unwrap(),
        vec![AffineDenominator::new(
            coefficients.parse("-m2").unwrap(),
            vec![coefficients.one()],
        )],
        Vec::new(),
        vec![coefficients.zero()],
    )
    .unwrap()
}

fn one_loop_family_with_base_guard(name: &str) -> IntegralFamily {
    let coefficients = CoefficientContext::new(["d", "m2"]);
    IntegralFamily::new(
        name,
        vec!["k".into()],
        Vec::new(),
        coefficients.clone(),
        coefficients.parse("d/m2").unwrap(),
        vec![AffineDenominator::new(
            coefficients.parse("-m2").unwrap(),
            vec![coefficients.one()],
        )],
        Vec::new(),
        vec![coefficients.zero()],
    )
    .unwrap()
}

fn context(family: &IntegralFamily) -> ParametricCoefficientContext {
    ParametricIbpGenerator::try_new(family)
        .unwrap()
        .generate()
        .unwrap()
        .context()
        .clone()
}

fn ordering(anchor: i64) -> ParametricEliminationOrdering {
    ParametricEliminationOrdering::try_new(IntegralOrderingPolicy::RustRedUnshiftedV1, [anchor])
        .unwrap()
}

#[test]
fn one_loop_boundary_is_regenerated_specialized_reeliminated_and_replayed() {
    let family = one_loop_family("conditional-reelimination-one-loop");
    let context = context(&family);
    let zero = IndexSpace::try_new(1).unwrap().zero();
    let source_assignment = PartialIndexAssignment::try_new([(0, 1)], 1, 1).unwrap();
    let compilation = GeneratedPartialReeliminationCompiler::compile(
        &family,
        &context,
        &[zero],
        source_assignment.clone(),
        ordering(1),
        GeneratedPartialReeliminationLimits::default(),
    )
    .unwrap();
    let GeneratedPartialReeliminationCompilation::Certified(certificate) = compilation else {
        panic!("the generated one-loop boundary system must retain its IBP row");
    };

    assert_eq!(
        certificate.schema(),
        GENERATED_PARTIAL_REELIMINATION_V2_SCHEMA
    );
    assert_eq!(
        certificate.authentication(),
        GeneratedPartialSourceAuthentication::CanonicalIbpLiExactTranslationsAndSparseSpecialization,
    );
    assert_eq!(certificate.assignment(), &source_assignment);
    assert_eq!(certificate.stats().canonical_rows(), 1);
    assert_eq!(certificate.stats().translations(), 1);
    assert_eq!(certificate.stats().expanded_rows(), 1);
    assert_eq!(certificate.stats().retained_rows(), 1);
    assert_eq!(certificate.stats().unsatisfiable_rows(), 0);
    assert_eq!(certificate.elimination_stats().source_rows(), 1);
    assert_eq!(certificate.elimination_stats().rank(), 1);
    assert_eq!(certificate.witnesses().len(), 1);
    assert!(matches!(
        certificate.witnesses()[0].canonical_row_id(),
        ParametricRowId::OrdinaryIbp {
            contraction_momentum: 0,
            differentiated_loop: 0,
        }
    ));
    assert!(matches!(
        certificate.witnesses()[0].outcome(),
        GeneratedPartialSourceRowOutcome::Retained { .. }
    ));
    assert_ne!(
        certificate.witnesses()[0].canonical_manifest(),
        certificate.witnesses()[0].translated_manifest(),
        "even the zero translation has an authenticated derived row identity",
    );

    let loci = certificate.centered_pivot_loci();
    assert_eq!(loci.len(), 1);
    let pivot = loci[0].original_pivot().values()[0];
    assert_eq!(
        loci[0].centered_assignment().entries(),
        &[(0, 1i64.checked_add(pivot).unwrap())],
        "centering by -pivot maps n_source=1 to n_center=1+pivot",
    );
    // For the tadpole IBP and this ordering the hard column is I(n+1).
    assert_eq!(pivot, 1);
    assert_eq!(loci[0].centered_assignment().entries(), &[(0, 2)]);
    certificate.replay(&family, &context).unwrap();
}

#[test]
fn translation_stencil_is_canonical_exact_and_provenance_bearing() {
    let family = one_loop_family("conditional-reelimination-stencil");
    let context = context(&family);
    let space = IndexSpace::try_new(1).unwrap();
    // Deliberately provide non-canonical order; the retained transcript is
    // lexicographic and therefore independent of caller container order.
    let translations = [space.zero(), space.shift([-1]).unwrap()];
    let compilation = GeneratedPartialReeliminationCompiler::compile(
        &family,
        &context,
        &translations,
        PartialIndexAssignment::try_new([(0, 2)], 1, 1).unwrap(),
        ordering(2),
        GeneratedPartialReeliminationLimits::default(),
    )
    .unwrap();
    let GeneratedPartialReeliminationCompilation::Certified(certificate) = compilation else {
        panic!("translated generated rows must yield a conditional system");
    };
    assert_eq!(certificate.translations()[0].values(), &[-1]);
    assert_eq!(certificate.translations()[1].values(), &[0]);
    assert_eq!(certificate.witnesses().len(), 2);
    assert_eq!(certificate.witnesses()[0].canonical_ordinal(), 0);
    assert_eq!(certificate.witnesses()[0].translation().values(), &[-1]);
    assert_eq!(certificate.witnesses()[1].translation().values(), &[0]);
    assert_ne!(
        certificate.witnesses()[0].translated_manifest(),
        certificate.witnesses()[1].translated_manifest(),
    );
    assert!(certificate.stats().transcript_bytes() > 0);
    assert!(certificate.stats().aggregate_source_terms() > 0);
    certificate.replay(&family, &context).unwrap();
}

#[test]
fn base_assumption_retains_the_exact_polynomial_and_typed_origins() {
    let family = one_loop_family_with_base_guard("conditional-reelimination-base-guard");
    let context = context(&family);
    let compilation = GeneratedPartialReeliminationCompiler::compile(
        &family,
        &context,
        &[IndexSpace::try_new(1).unwrap().zero()],
        PartialIndexAssignment::try_new([(0, 1)], 1, 1).unwrap(),
        ordering(1),
        GeneratedPartialReeliminationLimits::default(),
    )
    .unwrap();
    let GeneratedPartialReeliminationCompilation::Certified(certificate) = compilation else {
        panic!("the guarded generated row must survive on this locus");
    };
    let lifted_m2 = context
        .lift(&family.coefficient_context().parameter("m2").unwrap())
        .unwrap();
    let expected = context.numerator_condition(&lifted_m2).unwrap();
    let assumption = certificate
        .base_assumptions()
        .iter()
        .find(|assumption| assumption.condition().polynomial() == &expected)
        .expect("the exact m2 != 0 family assumption must be retained");
    assert_eq!(
        assumption.origin_count(),
        assumption.condition().origins().len()
    );
    assert!(assumption.condition().origins().contains(
        &GuardOrigin::FamilyInputCoefficientDenominator {
            location: CoefficientLocation::Dimension,
        },
    ));
    assert!(
        assumption
            .condition()
            .origins()
            .iter()
            .any(|origin| matches!(
                origin,
                GuardOrigin::PartialIndexSpecialization { assignments }
                    if assignments.as_ref() == [(0, 1)]
            ))
    );
    assert!(
        assumption
            .condition()
            .origins()
            .iter()
            .any(|origin| matches!(origin, GuardOrigin::RelationConditionAttached { .. }))
    );
    assert!(
        assumption
            .manifest()
            .starts_with("rustred-generated-partial-base-assumption-v2|polynomial=")
    );
    assert!(
        assumption
            .manifest()
            .contains(":rustred-parametric-polynomial-sparse-v1|variables=")
    );
    assert!(assumption.manifest().contains("|terms="));
    assert!(assumption.manifest().contains("|origins="));
    certificate.replay(&family, &context).unwrap();
}

#[test]
fn malformed_stencils_and_aggregate_limits_fail_closed() {
    let family = one_loop_family("conditional-reelimination-adversarial");
    let context = context(&family);
    let space = IndexSpace::try_new(1).unwrap();
    let assignment = PartialIndexAssignment::try_new([(0, 1)], 1, 1).unwrap();
    let limits = GeneratedPartialReeliminationLimits::default();

    assert!(matches!(
        GeneratedPartialReeliminationCompiler::compile(
            &family,
            &context,
            &[space.shift([1]).unwrap()],
            assignment.clone(),
            ordering(1),
            limits,
        ),
        Err(GeneratedPartialReeliminationError::MissingZeroTranslation),
    ));
    assert!(matches!(
        GeneratedPartialReeliminationCompiler::compile(
            &family,
            &context,
            &[space.zero(), space.zero()],
            assignment.clone(),
            ordering(1),
            limits,
        ),
        Err(GeneratedPartialReeliminationError::DuplicateTranslation { ref values })
            if values.as_ref() == [0]
    ));

    let mut bounded = limits;
    bounded.max_canonical_rows = 0;
    assert!(matches!(
        GeneratedPartialReeliminationCompiler::compile(
            &family,
            &context,
            &[space.zero()],
            assignment.clone(),
            ordering(1),
            bounded,
        ),
        Err(GeneratedPartialReeliminationError::ResourceLimit {
            resource: "canonical generated rows",
            requested: 1,
            limit: 0,
        })
    ));

    let mut bounded = limits;
    bounded.max_aggregate_source_terms = 0;
    assert!(matches!(
        GeneratedPartialReeliminationCompiler::compile(
            &family,
            &context,
            &[space.zero()],
            assignment,
            ordering(1),
            bounded,
        ),
        Err(GeneratedPartialReeliminationError::ResourceLimit {
            resource: "aggregate partial source terms",
            ..
        })
    ));
}

#[test]
fn replay_rejects_wrong_family_and_context_and_centering_overflow_is_typed() {
    let family = one_loop_family("conditional-reelimination-scope");
    let context = context(&family);
    let zero = IndexSpace::try_new(1).unwrap().zero();
    let compilation = GeneratedPartialReeliminationCompiler::compile(
        &family,
        &context,
        &[zero.clone()],
        PartialIndexAssignment::try_new([(0, 1)], 1, 1).unwrap(),
        ordering(1),
        GeneratedPartialReeliminationLimits::default(),
    )
    .unwrap();
    let GeneratedPartialReeliminationCompilation::Certified(certificate) = compilation else {
        panic!("expected a retained generated system");
    };

    let wrong_family = one_loop_family("conditional-reelimination-other-family");
    assert!(matches!(
        certificate.replay(&wrong_family, &context),
        Err(GeneratedPartialReeliminationError::WrongFamily)
    ));
    let wrong_context = ParametricCoefficientContext::try_new(
        family.coefficient_context(),
        "wrong-conditional-index-scope",
        1,
    )
    .unwrap();
    assert!(matches!(
        certificate.replay(&family, &wrong_context),
        Err(GeneratedPartialReeliminationError::WrongContext)
    ));

    assert!(matches!(
        GeneratedPartialReeliminationCompiler::compile(
            &family,
            &context,
            &[zero],
            PartialIndexAssignment::try_new([(0, i64::MAX)], 1, 1).unwrap(),
            ordering(i64::MAX - 1),
            GeneratedPartialReeliminationLimits::default(),
        ),
        Err(
            GeneratedPartialReeliminationError::CenteredAssignmentOverflow {
                pivot: 0,
                position: 0,
            }
        )
    ));
}
