//! End-to-end regression of the closure oracle on real walks, with no
//! dependency on run directories: the two-loop sunset family (in-repo family
//! text), candidate owners generated by `family_candidates` and split into
//! the single-sector owner bundles the shared-owner loader accepts, a
//! checkpointed Ordered walk built by the production argv parser, and
//! `owner_domain_walk_verify_closure` on its final generation with the
//! published result.json bound.
//!
//! Three fixtures. DRAINED: five queries (one absorbed: four roots), dispatch
//! lookahead 1 so that successors beyond the horizon become aliases, and two
//! sub-sector D >= 5 queries whose boxes contain the high-D slice of later
//! successors, so that those become partial records anchored on them. It has
//! natives, aliases and partials, and all roots close. FRONTIER: the 011
//! owner is left out of the selection, so successors into that sector stay
//! open: one of two roots closes. ROUTED: the FRONTIER walk with a verified
//! loop-momentum route 011 -> 110 (q1 -> q1 - q2 maps P2, P3 onto P2, P1):
//! the successors into sector 011 become Route natives that each route one
//! Apply domain into owner 110, and both roots close.
//!
//! The drained walk must PASS (with and without `--require-closure`) and pass
//! the gate (verdict PASS, every root independently verified); partial or no
//! re-inspection must be INCOMPLETE (never PASS); every mutation must give its
//! exact violation-class set, with the per-node F10 classes firing.
pub(super) use super::test_scratch::{Scratch, scratch};
use super::*;
use crate::application::candidate_bundle::split_generated_candidate_bundle;
use crate::{FamilyCandidatesRequest, family_candidates, owner_domain_walk_with_progress};
use std::collections::BTreeSet;
use std::ffi::OsString;
use std::path::Path;

const SUNSET: &str = r#"
schema="rustred.project.toml.v1"
[family]
name="verify_closure_sunset"
loop_momenta=["q1","q2"]
external_momenta=[]
dimension="d"
[[family.denominators]]
id="P1"
expression="q1^2-1"
[[family.denominators]]
id="P2"
expression="q2^2-1"
[[family.denominators]]
id="P3"
expression="(q1+q2)^2-1"
[target]
powers=[1,1,1]
"#;

/// Owners of the sunset family at candidate rank `rank`, one bundle per
/// sector (except the masks in `omit`), written under `dir`, with the
/// `initial_frontier_routes` given; returns the selection JSON text.
pub(super) fn write_owners(dir: &Path, rank: u32, omit: &[&str], routes: &Value) -> String {
    let mut generation = FamilyCandidatesRequest::new(SUNSET);
    generation.max_numerator_rank = Some(rank);
    let bundle = family_candidates(generation).unwrap();
    let shards = split_generated_candidate_bundle(bundle.bundle()).unwrap();
    let mut owners = Vec::new();
    let mut fingerprint = String::new();
    for (mask, bytes, family) in shards {
        fingerprint = family;
        if omit.contains(&mask.as_str()) {
            continue;
        }
        let name = format!("owner-{mask}.rrbin");
        std::fs::write(dir.join(&name), &bytes).unwrap();
        owners.push(json!({"path": name, "bytes": bytes.len(), "mask": mask}));
    }
    json!({"family_fingerprint": fingerprint, "owners": owners, "initial_frontier_routes": routes})
        .to_string()
}

/// The production walk argv over `dir` (selection.json, queries.json).
pub(super) fn walk_argv(dir: &Path, lookahead: u32, extra: &[&str]) -> Vec<OsString> {
    let lookahead = lookahead.to_string();
    let path = |name: &str| dir.join(name).into_os_string();
    let mut argv: Vec<OsString> = vec!["rustred".into(), "owner-domain-match".into()];
    for (option, value) in [
        ("--manifest", path("selection.json")),
        ("--owner-base", dir.as_os_str().to_owned()),
        ("--output", path("result.json")),
        ("--queries", path("queries.json")),
        ("--checkpoint", path("checkpoint")),
    ] {
        argv.push(option.into());
        argv.push(value);
    }
    for flag in [
        "--follow-successors",
        "--workers",
        "1",
        "--transfer-unreserved-lookahead",
        lookahead.as_str(),
        "--publication-policy",
        "ordered",
        "--route-domain-overcover",
        "--reuse-initial-d-bands",
        "--bounded-refinement-axes",
        "finite-axes",
        "--no-progress",
    ]
    .iter()
    .copied()
    .chain(extra.iter().copied())
    {
        argv.push(flag.into());
    }
    argv
}

/// Run the walk in-process and publish result.json as the CLI does.
pub(super) fn walk(dir: &Path, request: &OwnerDomainWalkRequest) -> Value {
    let result =
        owner_domain_walk_with_progress(request.clone(), &AtomicBool::new(false), |_| {}).unwrap();
    let file = std::fs::File::create(dir.join("result.json")).unwrap();
    result.write_json(std::io::BufWriter::new(file)).unwrap();
    serde_json::from_slice(&std::fs::read(dir.join("result.json")).unwrap()).unwrap()
}

pub(super) struct Run {
    pub dir: Scratch,
    pub request: OwnerDomainWalkRequest,
    pub result: Value,
}

pub(super) struct Fixture<'a> {
    pub rank: u32,
    pub queries: Value,
    pub lookahead: u32,
    pub omit: &'a [&'a str],
    /// `initial_frontier_routes` of the selection (a JSON array).
    pub routes: Value,
}

pub(super) fn run(label: &str, fixture: &Fixture, extra: &[&str]) -> Run {
    let dir = scratch(label);
    let selection = write_owners(&dir.0, fixture.rank, fixture.omit, &fixture.routes);
    std::fs::write(dir.0.join("selection.json"), selection).unwrap();
    std::fs::write(dir.0.join("queries.json"), fixture.queries.to_string()).unwrap();
    let argv = walk_argv(&dir.0, fixture.lookahead, extra);
    let request = crate::cli::walk_request_from_argv(argv).unwrap();
    let result = walk(&dir.0, &request);
    Run {
        dir,
        request,
        result,
    }
}

pub(super) fn verify_run(
    run: &Run,
    tweak: impl FnOnce(&mut OwnerDomainWalkVerifyOptions),
) -> Value {
    let mut options = OwnerDomainWalkVerifyOptions::new(run.dir.0.join("checkpoint"));
    options.threads = 2;
    options.result = Some(run.dir.0.join("result.json"));
    tweak(&mut options);
    owner_domain_walk_verify_closure(&run.request, &options, &AtomicBool::new(false), |_| {})
        .unwrap()
}

pub(super) fn classes(report: &Value) -> BTreeSet<String> {
    report["violations_by_class"]
        .as_object()
        .unwrap()
        .keys()
        .cloned()
        .collect()
}

fn record_kinds(result: &Value) -> BTreeMap<String, u64> {
    let mut kinds = BTreeMap::new();
    for row in result["domains"].as_array().unwrap() {
        let key = format!(
            "{}/{}",
            row["record_kind"].as_str().unwrap_or("?"),
            row["phase"].as_str().unwrap_or("?")
        );
        *kinds.entry(key).or_insert(0) += 1;
    }
    kinds
}

/// Exploration aid (not a regression test): walk RUSTRED_E2E_QUERIES (JSON
/// text) at candidate rank RUSTRED_E2E_RANK (lookahead RUSTRED_E2E_LOOKAHEAD,
/// owner masks RUSTRED_E2E_OMIT left out, routes RUSTRED_E2E_ROUTES) and
/// print the record census and every mutation's verdict and violation classes.
#[test]
#[ignore = "exploration aid; run explicitly"]
fn explore_sunset_fixture() {
    let queries: Value =
        serde_json::from_str(&std::env::var("RUSTRED_E2E_QUERIES").unwrap()).unwrap();
    let rank: u32 = std::env::var("RUSTRED_E2E_RANK").map_or(2, |r| r.parse().unwrap());
    let extra: Vec<String> = std::env::var("RUSTRED_E2E_EXTRA")
        .map(|e| e.split_whitespace().map(str::to_owned).collect())
        .unwrap_or_default();
    let extra: Vec<&str> = extra.iter().map(String::as_str).collect();
    let lookahead = std::env::var("RUSTRED_E2E_LOOKAHEAD").map_or(256, |l| l.parse().unwrap());
    let omit = std::env::var("RUSTRED_E2E_OMIT").unwrap_or_default();
    let omit: Vec<&str> = omit.split_whitespace().collect();
    let routes: Value = std::env::var("RUSTRED_E2E_ROUTES")
        .map_or(json!([]), |r| serde_json::from_str(&r).unwrap());
    let fixture = Fixture {
        rank,
        queries,
        lookahead,
        omit: &omit,
        routes,
    };
    let run = run("explore", &fixture, &extra);
    let result = &run.result;
    println!(
        "{}",
        json!({"dir": run.dir.0, "status": result["status"], "frontiers": result["frontiers"],
            "failed_nodes": result["failed_nodes"], "committed_domains": result["committed_domains"],
            "partial_initial_inspections": result["partial_initial_inspections"],
            "kinds": record_kinds(result)})
    );
    for require in [false, true] {
        let base = verify_run(&run, |o| o.require_closure = require);
        println!(
            "{}",
            json!({"require": require, "mutation": null, "verdict": base["verdict"],
                "classes": base["violations_by_class"], "counts": base["counts"],
                "tally": base["reinspection"]["tally"]})
        );
        for kind in OwnerDomainWalkVerifyMutation::ALL {
            let report = verify_run(&run, |o| {
                o.require_closure = require;
                o.mutation = Some(kind);
            });
            println!(
                "{}",
                json!({"require": require, "mutation": kind.name(), "verdict": report["verdict"],
                    "applied": report["mutation"]["applied"], "reason": report["mutation"]["reason"],
                    "classes": report["violations_by_class"],
                    "roots_oracle_closed": report["counts"]["roots_oracle_closed"],
                    "covered_along_alias_chain": report["reinspection"]["tally"]["covered_along_alias_chain"]})
            );
        }
    }
}

fn query(id: &str, owner: &str, upper: [u64; 3], rank: u32, a: u64, d: i64) -> Value {
    json!({"id": id, "owner": owner, "lower": [0, 0, 0], "upper": upper, "max_numerator_rank": rank,
        "power_bounds": {"max_positive_power": a, "min_power_difference": d, "max_power_difference": null}})
}

fn queries(rows: Vec<Value>) -> Value {
    json!({"schema": "rustred.owner-domain-queries.json.v2", "queries": rows})
}

fn drained() -> Run {
    let mut input = queries(vec![
        query("anchor011", "011", [0, 5, 0], 0, 7, 5),
        query("anchor110", "110", [5, 0, 0], 0, 7, 5),
        query("anchor", "111", [3, 3, 3], 2, 5, 2),
        query("big", "111", [5, 5, 5], 2, 8, 0),
        query("big-inner", "111", [4, 4, 4], 2, 6, 1),
    ]);
    input["query_roles"] = json!({"required":["big","big-inner"],
        "auxiliary":["anchor011","anchor110","anchor"]});
    let fixture = Fixture {
        rank: 2,
        queries: input,
        lookahead: 1,
        omit: &[],
        routes: json!([]),
    };
    run("drained", &fixture, &[])
}

fn frontier_queries() -> Value {
    queries(vec![
        query("anchor", "111", [3, 3, 3], 2, 5, 2),
        query("s101", "101", [4, 0, 4], 1, 6, 1),
    ])
}

fn frontier() -> Run {
    let fixture = Fixture {
        rank: 2,
        queries: frontier_queries(),
        lookahead: 256,
        omit: &["011"],
        routes: json!([]),
    };
    run("frontier", &fixture, &[])
}

/// The frontier walk with a verified route 011 -> 110: source momenta
/// q = M k with M = [[1, -1], [0, 1]] (q1 = k1 - k2, q2 = k2) send
/// P2 = q2^2 - 1 to k2^2 - 1 and P3 = (q1 + q2)^2 - 1 to k1^2 - 1.
fn routed() -> Run {
    let fixture = Fixture {
        rank: 2,
        queries: frontier_queries(),
        lookahead: 256,
        omit: &["011"],
        routes: json!([{"source_mask": "011", "owner_mask": "110", "requires_transport": true,
            "source_to_representative": [["1", "-1"], ["0", "1"]],
            "owner_to_representative": [["1", "0"], ["0", "1"]]}]),
    };
    run("routed", &fixture, &[])
}

fn class_counts(report: &Value) -> BTreeMap<String, u64> {
    report["violations_by_class"]
        .as_object()
        .unwrap()
        .iter()
        .map(|(k, v)| (k.clone(), v.as_u64().unwrap()))
        .collect()
}

fn gate(report: &Value) -> bool {
    report["verdict"] == "PASS"
        && report["roots_total"].as_u64().is_some_and(|t| t >= 1)
        && report["roots_independently_verified"] == report["roots_total"]
        && report["family_closure_claim"] == false
}

#[test]
fn drained_sunset_walk_passes_the_gate_with_every_record_kind_and_binding() {
    let run = drained();
    let kinds = record_kinds(&run.result);
    for kind in [
        "native_inspection/Apply",
        "delegated_not_inspected/Apply",
        "partial_initial_overlap_inspection/Apply",
    ] {
        assert!(kinds.get(kind).is_some_and(|&n| n > 0), "{kind}: {kinds:?}");
    }
    let natives =
        kinds["native_inspection/Apply"] + kinds["partial_initial_overlap_inspection/Apply"];
    let partials = kinds["partial_initial_overlap_inspection/Apply"];
    for require in [false, true] {
        let report = verify_run(&run, |o| o.require_closure = require);
        assert_eq!(
            report["verdict"], "PASS",
            "{require}: {}",
            report["violations"]
        );
        assert!(classes(&report).is_empty());
        assert!(gate(&report), "{require}");
        // Query-to-root mapping: five queries, one absorbed, four roots.
        assert_eq!(report["queries"]["count"], 5);
        assert_eq!(report["roots_total"], 4);
        assert_eq!(report["counts"]["roots_oracle_closed"], 4);
        let certification = &report["certification"]["classes"];
        assert_eq!(certification["physics"]["total"], 2);
        assert_eq!(certification["physics"]["absorbed"], 1);
        assert_eq!(certification["helper"]["total"], 3);
        // Request / owner digest binding and the result.json binding.
        assert_eq!(report["checkpoint"]["request_binding_matches"], true);
        assert_eq!(report["checkpoint"]["owner_digests_match"], true);
        let binding = &report["result_binding"];
        assert_eq!(binding["generation_matches"], true);
        assert_eq!(binding["records_mismatched"], 0);
        assert_eq!(binding["records_compared"], report["counts"]["domains"]);
        // Per-node F10: every native and partial re-inspected under the
        // reference, event parity enforced (no lever differs from the run).
        let tally = &report["reinspection"]["tally"];
        assert_eq!(tally["inspected"].as_u64(), Some(natives));
        assert!(tally["events"].as_u64().unwrap() > 0);
        assert_eq!(tally["uncovered"], 0);
        assert_eq!(tally["count_mismatches_under_disabled_levers"], 0);
        assert_eq!(report["reference"]["native_levers"], "Off");
        assert_eq!(report["reference"]["count_parity"], "enforced");
        // Partial-anchor containment, and the exact union cover agreeing.
        let union = &report["containment"]["partial_union_cover"];
        assert_eq!(union["checks"].as_u64(), Some(partials));
        assert_eq!(union["covered"].as_u64(), Some(partials));
        assert_eq!(union["disagreements_with_slice_inclusion"], 0);
        assert_eq!(
            report["containment"]["exact_vs_brute_force_disagreements"],
            0
        );
    }
}

#[test]
fn partial_or_no_reinspection_is_incomplete_even_over_a_defect() {
    let run = drained();
    for (reinspect, mutation) in [
        (OwnerDomainWalkVerifyReinspect::None, None),
        (
            OwnerDomainWalkVerifyReinspect::Sample { count: 3, seed: 1 },
            None,
        ),
        (
            OwnerDomainWalkVerifyReinspect::None,
            Some(OwnerDomainWalkVerifyMutation::DroppedEdge),
        ),
    ] {
        let report = verify_run(&run, |o| {
            o.require_closure = true;
            o.reinspect = reinspect;
            o.mutation = mutation;
        });
        assert_eq!(
            report["verdict"], "INCOMPLETE",
            "{reinspect:?} {mutation:?}"
        );
        assert!(classes(&report).is_empty());
        assert_eq!(report["roots_independently_verified"], 0);
        assert!(!gate(&report));
    }
}

#[test]
fn frontier_sunset_walk_is_consistent_but_not_closed() {
    let run = frontier();
    assert!(run.result["frontiers"].as_u64().unwrap() > 0);
    let plain = verify_run(&run, |_| {});
    assert_eq!(plain["verdict"], "PASS", "{}", plain["violations"]);
    assert_eq!(plain["roots_total"], 2);
    assert_eq!(plain["counts"]["roots_oracle_closed"], 1);
    // Consistent, but not every root is closed: the gate refuses it.
    assert_eq!(plain["roots_independently_verified"], 1);
    assert!(!gate(&plain));
    let required = verify_run(&run, |o| o.require_closure = true);
    assert_eq!(required["verdict"], "FAIL");
    assert_eq!(
        class_counts(&required),
        BTreeMap::from([("closure_required".into(), 1)])
    );
}

#[test]
fn routed_sunset_walk_routes_apply_domains_through_route_natives() {
    let run = routed();
    let kinds = record_kinds(&run.result);
    assert_eq!(kinds.get("native_inspection/Route"), Some(&3), "{kinds:?}");
    assert_eq!(run.result["frontiers"], 0);
    let report = verify_run(&run, |o| o.require_closure = true);
    assert_eq!(report["verdict"], "PASS", "{}", report["violations"]);
    assert!(gate(&report));
    assert_eq!(report["roots_total"], 2);
    let tally = &report["reinspection"]["tally"];
    // Every Route native routes one Apply domain; each is covered.
    assert_eq!(tally["admitted_routed_domains"], 3);
    assert_eq!(tally["uncovered"], 0);
    assert_eq!(tally["inspected"], report["counts"]["domains"]);
}

#[test]
fn a_route_partial_fails_on_its_phase_even_without_reinspection() {
    use OwnerDomainWalkVerifyMutation as M;
    let drained = drained();
    let structural = verify_run(&drained, |o| {
        o.require_closure = true;
        o.reinspect = OwnerDomainWalkVerifyReinspect::None;
        o.mutation = Some(M::RoutePartial);
    });
    assert_eq!(structural["mutation"]["applied"], true);
    assert_eq!(structural["verdict"], "FAIL");
    assert_eq!(
        class_counts(&structural),
        BTreeMap::from([("partial_phase".into(), 1)])
    );
    // With F10 the reference routes the flipped residual (event count) and
    // the parents' Apply successors no longer find a same-phase target.
    let full = verify_run(&drained, |o| {
        o.require_closure = true;
        o.mutation = Some(M::RoutePartial);
    });
    assert_eq!(full["verdict"], "FAIL");
    assert_eq!(
        class_counts(&full),
        BTreeMap::from([
            ("event_parity".into(), 1),
            ("partial_phase".into(), 1),
            ("successor_uncovered".into(), 4)
        ])
    );
    assert!(!gate(&full));
}

#[test]
fn every_mutation_gives_its_exact_violation_classes() {
    use OwnerDomainWalkVerifyMutation as M;
    let drained = drained();
    let frontier = frontier();
    let routed = routed();
    // (fixture, mutation, exact classes with --require-closure, exact counts
    // of the single-node classes). Per-node F10 classes (frontier_parity,
    // error_parity, event_parity, successor_parity, successor_uncovered) are
    // distinct from the global counters (frontier_counter, native_counter).
    let rows: Vec<(&Run, M, &[&str], &[(&str, u64)])> = vec![
        (&drained, M::DroppedEdge, &["successor_uncovered"], &[]),
        (&drained, M::InjectedFalseHit, &["successor_uncovered"], &[]),
        (
            &drained,
            M::RetargetedAlias,
            &["alias_containment"],
            &[("alias_containment", 1)],
        ),
        (
            &drained,
            M::RetargetedAnchor,
            &["partial_anchor", "partial_union_cover"],
            &[("partial_anchor", 1), ("partial_union_cover", 1)],
        ),
        // Partial-anchor well-foundedness: the anchor edge moves with the
        // link, the residual inspection is unchanged, only the anchor rules
        // fire (containment is not judged against an ill-founded anchor).
        (
            &drained,
            M::SelfAnchoredPartial,
            &["partial_anchor_kind", "partial_anchor_order"],
            &[("partial_anchor_kind", 1), ("partial_anchor_order", 1)],
        ),
        (
            &drained,
            M::PartialAsAnchor,
            &["partial_anchor_kind", "partial_anchor_order"],
            &[("partial_anchor_kind", 1), ("partial_anchor_order", 1)],
        ),
        (
            &drained,
            M::PartialAnchorCycle,
            &["partial_anchor_kind", "partial_anchor_order"],
            &[("partial_anchor_kind", 2), ("partial_anchor_order", 2)],
        ),
        (
            &drained,
            M::NonInitialAnchor,
            &["partial_anchor_order"],
            &[("partial_anchor_order", 1)],
        ),
        // The D = cut - 1 layer inspected by nobody: the exact union cover
        // fails (F10 re-inspects the derived D < cut slice, so no count moves).
        (
            &drained,
            M::ShrunkResidual,
            &["partial_residual", "partial_union_cover"],
            &[("partial_residual", 1), ("partial_union_cover", 1)],
        ),
        // Route natives: a routed Apply domain's only covering edge, and a
        // Route native's event count.
        (
            &routed,
            M::DroppedRoutedEdge,
            &["successor_uncovered"],
            &[("successor_uncovered", 1)],
        ),
        (
            &routed,
            M::RoutedFalseHit,
            &["successor_uncovered"],
            &[("successor_uncovered", 1)],
        ),
        (
            &routed,
            M::MiscountedRouteEvents,
            &["event_parity"],
            &[("event_parity", 1)],
        ),
        (
            &drained,
            M::SealWithFrontier,
            &[
                "closure_required",
                "false_closure",
                "frontier_counter",
                "frontier_parity",
                "seal_parity",
            ],
            &[
                ("frontier_counter", 1),
                ("frontier_parity", 1),
                ("seal_parity", 1),
            ],
        ),
        (
            &drained,
            M::SealWithError,
            &[
                "closure_required",
                "error_parity",
                "false_closure",
                "native_counter",
                "seal_parity",
            ],
            &[
                ("error_parity", 1),
                ("native_counter", 1),
                ("seal_parity", 1),
            ],
        ),
        (
            &drained,
            M::HiddenError,
            &["error_parity"],
            &[("error_parity", 1)],
        ),
        (
            &drained,
            M::MiscountedEvents,
            &["event_parity"],
            &[("event_parity", 1)],
        ),
        (
            &drained,
            M::MiscountedSuccessors,
            &["successor_parity"],
            &[("successor_parity", 1)],
        ),
        (
            &drained,
            M::RemappedQuery,
            &["root_mapping"],
            &[("root_mapping", 1)],
        ),
        (&drained, M::ForeignRequest, &["binding"], &[("binding", 1)]),
        (&drained, M::ForeignOwners, &["binding"], &[("binding", 1)]),
        (
            &drained,
            M::MismatchedResult,
            &["result_binding"],
            &[("result_binding", 1)],
        ),
        (
            &frontier,
            M::DroppedFrontierRecord,
            &["closure_required", "frontier_counter", "frontier_parity"],
            &[("frontier_counter", 1), ("frontier_parity", 1)],
        ),
        (
            &frontier,
            M::HiddenFrontier,
            &["closure_required", "frontier_parity"],
            &[("frontier_parity", 1)],
        ),
        (
            &frontier,
            M::SealWithFrontier,
            &["closure_required", "seal_parity"],
            &[("seal_parity", 1)],
        ),
        (
            &frontier,
            M::HiddenError,
            &["closure_required", "error_parity"],
            &[("error_parity", 1)],
        ),
        (
            &frontier,
            M::MiscountedEvents,
            &["closure_required", "event_parity"],
            &[("event_parity", 1)],
        ),
    ];
    for (run, mutation, expected, counts) in rows {
        let report = verify_run(run, |o| {
            o.require_closure = true;
            o.mutation = Some(mutation);
        });
        let label = mutation.name();
        assert_eq!(
            report["mutation"]["applied"], true,
            "{label}: {}",
            report["mutation"]
        );
        assert_eq!(report["verdict"], "FAIL", "{label}");
        let expected: BTreeSet<String> = expected.iter().map(|c| c.to_string()).collect();
        assert_eq!(
            classes(&report),
            expected,
            "{label}: {}",
            report["violations_by_class"]
        );
        let got = class_counts(&report);
        for (class, count) in counts {
            assert_eq!(got.get(*class), Some(count), "{label}: {class}");
        }
        assert!(!gate(&report), "{label}");
    }
    // Positive control: an alias-chain detour must PASS through the chain.
    let detour = verify_run(&drained, |o| {
        o.require_closure = true;
        o.mutation = Some(M::AliasChainDetour);
    });
    assert_eq!(
        detour["mutation"]["applied"], true,
        "{}",
        detour["mutation"]
    );
    assert_eq!(detour["verdict"], "PASS", "{}", detour["violations"]);
    assert!(
        detour["reinspection"]["tally"]["covered_along_alias_chain"]
            .as_u64()
            .unwrap()
            >= 1
    );
    assert!(gate(&detour));
}
