//! W0.11 (D6): verified literal ("all-slot") automorphism group of a vacuum
//! integral family, and its stabilizer per saved owner mask.
//!
//! A literal automorphism is a unimodular loop map A (l_source = A l_target)
//! under which every family line momentum q_i is mapped to +-q_{pi(i)}, so the
//! denominators q_i^2 - m^2 (one common mass here) are permuted and every
//! integral satisfies I(n) = I(pi n) exactly. Candidate generation below is
//! plain integer bookkeeping over the line coefficient rows (no algebra); the
//! proof boundary is RustRed's own authenticated path:
//! `sector::symmetry::verify` (exact derivation + independent replay of the
//! induced scalar-product and denominator maps, Symbolica-backed),
//! `sector::symmetry::permutation::compile` (unit Jacobian, pure denominator
//! permutation), and `Canonicalizer::try_new`, which derives the complete
//! finite group generated by the authenticated permutations.
//!
//! Symbolica check (owner rule 4): the vendored 953e26e2 and upstream dev
//! 445b882d expose matrices over Q and graph automorphisms (graphica) but no
//! loop-momentum automorphism search of an integral family; the search here is
//! combinatorial and every accepted element is authenticated by the in-tree
//! verifier, which does the algebra through Symbolica.
//!
//! Usage: wv-family-automorphisms FAMILY.toml OWNERS.txt ROUTE_MASKS.txt
//!        EXPECTED_FINGERPRINT.txt OUT.json
//!   OWNERS.txt / ROUTE_MASKS.txt: one 0/1 mask string per line (slot order).
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::fs;

use rustred::input::{Compiler, Limits, LoweringLimits, TextProject, TextPropagator};
use rustred::sector::OrderingPolicy;
use rustred::sector::symmetry::{
    self, CanonicalizationLimits, Canonicalizer, CoefficientMatrix, MomentumMap, permutation,
};

struct Toml {
    name: String,
    loops: Vec<String>,
    dimension: String,
    denominators: Vec<(String, String)>,
    target: Vec<i64>,
    numerator: Option<String>,
}

fn quoted(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = line;
    while let Some(a) = rest.find('"') {
        let tail = &rest[a + 1..];
        let b = tail.find('"').expect("closing quote");
        out.push(tail[..b].to_string());
        rest = &tail[b + 1..];
    }
    out
}

/// Minimal reader for the explicit `rustred.project.toml.v1` family layout
/// used by `examples/input/tide_five_loop.toml` (no general TOML support).
fn read_toml(text: &str) -> Toml {
    let mut t = Toml {
        name: String::new(),
        loops: Vec::new(),
        dimension: String::new(),
        denominators: Vec::new(),
        target: Vec::new(),
        numerator: None,
    };
    let mut section = String::new();
    let mut pending_id: Option<String> = None;
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line.starts_with('[') {
            section = line.trim_matches(|c| c == '[' || c == ']').to_string();
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let (key, value) = (key.trim(), value.trim());
        match (section.as_str(), key) {
            ("family", "name") => t.name = quoted(value)[0].clone(),
            ("family", "loop_momenta") => t.loops = quoted(value),
            ("family", "external_momenta") => assert!(quoted(value).is_empty(), "vacuum only"),
            ("family", "dimension") => t.dimension = quoted(value)[0].clone(),
            ("family.denominators", "id") => pending_id = Some(quoted(value)[0].clone()),
            ("family.denominators", "expression") => t.denominators.push((
                pending_id.take().expect("id before expression"),
                quoted(value)[0].clone(),
            )),
            ("family.denominators", other) => panic!("unsupported denominator key {other}"),
            ("target", "powers") => {
                t.target = value
                    .trim_matches(|c| c == '[' || c == ']')
                    .split(',')
                    .map(|x| x.trim().parse().unwrap())
                    .collect()
            }
            ("target", "numerator") => t.numerator = Some(quoted(value)[0].clone()),
            _ => {}
        }
    }
    t
}

/// Coefficient row of a line momentum over the loop momenta, from
/// "(k1-k3)^2-1" / "k1^2-1" (integer bookkeeping only).
fn line_row(expression: &str, loops: &[String]) -> (Vec<i64>, String) {
    let e: String = expression.chars().filter(|c| !c.is_whitespace()).collect();
    let (momentum, mass) = e.split_once("^2").expect("line square");
    let momentum = momentum.trim_start_matches('(').trim_end_matches(')');
    let mut row = vec![0i64; loops.len()];
    let bytes = momentum.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        let sign = match bytes[i] {
            b'+' => {
                i += 1;
                1
            }
            b'-' => {
                i += 1;
                -1
            }
            _ => 1,
        };
        let start = i;
        while i < bytes.len() && bytes[i] != b'+' && bytes[i] != b'-' {
            i += 1;
        }
        let symbol = &momentum[start..i];
        let k = loops
            .iter()
            .position(|l| l == symbol)
            .unwrap_or_else(|| panic!("momentum {symbol}"));
        row[k] += sign;
    }
    (row, mass.to_string())
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    assert_eq!(
        args.len(),
        6,
        "usage: FAMILY.toml OWNERS.txt ROUTE_MASKS.txt EXPECTED_FINGERPRINT.txt OUT.json"
    );
    let toml = read_toml(&fs::read_to_string(&args[1]).unwrap());
    let owners: Vec<String> = fs::read_to_string(&args[2])
        .unwrap()
        .lines()
        .map(str::to_string)
        .filter(|l| !l.is_empty())
        .collect();
    let routes: Vec<String> = fs::read_to_string(&args[3])
        .unwrap()
        .lines()
        .map(str::to_string)
        .filter(|l| !l.is_empty())
        .collect();
    let expected = fs::read_to_string(&args[4]).unwrap().trim().to_string();
    let n = toml.denominators.len();
    let loops = toml.loops.len();
    assert_eq!(toml.target.len(), n);

    // Family through the same explicit-project path as the application.
    let project = Compiler::new(Limits::default())
        .unwrap()
        .compile_text(TextProject {
            name: Some(toml.name.clone()),
            parameters: None,
            loop_momenta: toml.loops.clone(),
            external_momenta: Vec::new(),
            dimension: toml.dimension.clone(),
            propagators: toml
                .denominators
                .iter()
                .zip(&toml.target)
                .map(|((id, expression), &power)| TextPropagator {
                    id: id.clone(),
                    expression: expression.clone(),
                    target_power: power,
                    power_shift: None,
                })
                .collect(),
            external_gram: Vec::new(),
            numerator: toml.numerator.clone(),
        })
        .unwrap();
    let family = project
        .into_lowered(LoweringLimits::default())
        .unwrap()
        .into_family();
    let fingerprint_match = family.fingerprint() == expected;
    eprintln!("family fingerprint matches the saved-owner selection: {fingerprint_match}");

    // Integer candidate search: rows of A are signed line rows (lines 0..loops
    // must be the unit loop momenta, as in the TIDE A5 basis).
    let lines: Vec<(Vec<i64>, String)> = toml
        .denominators
        .iter()
        .map(|(_, e)| line_row(e, &toml.loops))
        .collect();
    for (k, (row, _)) in lines.iter().take(loops).enumerate() {
        assert!(
            row.iter().enumerate().all(|(j, &x)| x == i64::from(j == k)),
            "line {k} is not k{}",
            k + 1
        );
    }
    let masses: BTreeSet<&str> = lines.iter().map(|l| l.1.as_str()).collect();
    let mut index: BTreeMap<Vec<i64>, usize> = BTreeMap::new();
    for (i, (row, _)) in lines.iter().enumerate() {
        index.insert(row.clone(), i);
        index.insert(row.iter().map(|x| -x).collect(), i);
    }
    let signed: Vec<(usize, i64)> = (0..n).flat_map(|i| [(i, 1), (i, -1)]).collect();
    let mut candidates = Vec::new();
    let mut tried = 0u64;
    let mut choice: Vec<(usize, i64)> = Vec::new();
    fn rec(
        k: usize,
        loops: usize,
        n: usize,
        signed: &[(usize, i64)],
        lines: &[(Vec<i64>, String)],
        index: &BTreeMap<Vec<i64>, usize>,
        choice: &mut Vec<(usize, i64)>,
        tried: &mut u64,
        out: &mut Vec<Vec<Vec<i64>>>,
    ) {
        if k == loops {
            *tried += 1;
            let a: Vec<Vec<i64>> = choice
                .iter()
                .map(|&(j, s)| lines[j].0.iter().map(|x| s * x).collect())
                .collect();
            let mut hit = vec![false; n];
            for (row, _) in lines {
                let img: Vec<i64> = (0..loops)
                    .map(|c| (0..loops).map(|r| row[r] * a[r][c]).sum())
                    .collect();
                match index.get(&img) {
                    Some(&t) if !hit[t] => hit[t] = true,
                    _ => return,
                }
            }
            out.push(a);
            return;
        }
        for &(j, s) in signed {
            if choice.iter().any(|c| c.0 == j) {
                continue;
            }
            choice.push((j, s));
            rec(k + 1, loops, n, signed, lines, index, choice, tried, out);
            choice.pop();
        }
    }
    rec(
        0,
        loops,
        n,
        &signed,
        &lines,
        &index,
        &mut choice,
        &mut tried,
        &mut candidates,
    );
    eprintln!(
        "integer candidates: {} of {} signed basis images",
        candidates.len(),
        tried
    );

    // Authenticate every candidate with the in-tree verifier + compiler.
    let context = family.coefficient_context();
    let mut verified = Vec::new();
    let mut rejected = 0usize;
    let mut compiled: BTreeMap<Vec<usize>, Vec<Vec<i64>>> = BTreeMap::new();
    for a in &candidates {
        let entries = a.iter().flatten().map(|&x| context.integer(x));
        let map = MomentumMap::new(
            CoefficientMatrix::try_new(loops, loops, entries).unwrap(),
            CoefficientMatrix::try_new(loops, 0, []).unwrap(),
            CoefficientMatrix::try_new(0, 0, []).unwrap(),
        );
        match symmetry::verify(&family, &family, map, Default::default())
            .map_err(|e| format!("{e:?}"))
            .and_then(|v| permutation::compile(&family, v).map_err(|e| format!("{e:?}")))
        {
            Ok(p) => {
                compiled
                    .entry(p.source_for_target().to_vec())
                    .or_insert_with(|| a.clone());
                verified.push(p);
            }
            Err(e) => {
                rejected += 1;
                eprintln!("rejected candidate {a:?}: {e}");
            }
        }
    }
    let verified_count = verified.len();
    let canonicalizer = Canonicalizer::try_new(
        OrderingPolicy::default(),
        verified,
        CanonicalizationLimits::default(),
    )
    .unwrap();
    let group: Vec<Vec<usize>> = canonicalizer
        .group_elements()
        .map(<[usize]>::to_vec)
        .collect();
    let closed = group.iter().all(|g| compiled.contains_key(g))
        && compiled.keys().all(|p| group.contains(p));
    eprintln!(
        "verified {verified_count}, rejected {rejected}, distinct permutations {}, group order {}, candidate set closed: {closed}",
        compiled.len(),
        group.len()
    );

    let bits = |m: &str| -> Vec<bool> { m.bytes().map(|b| b == b'1').collect() };
    // Image mask of a permutation g (source_for_target): target slot j is
    // active iff source slot g[j] is.
    let image = |g: &[usize], m: &[bool]| -> String {
        g.iter().map(|&s| if m[s] { '1' } else { '0' }).collect()
    };
    let owner_set: BTreeSet<&str> = owners.iter().map(String::as_str).collect();
    let mut js = String::new();
    write!(js, "{{\"schema\":\"rustred.wv.family-automorphisms.v1\",\"family_fingerprint_matches_selection\":{fingerprint_match},").unwrap();
    write!(
        js,
        "\"line_masses\":{:?},\"integer_candidates\":{},\"signed_basis_images_tried\":{tried},",
        masses.iter().collect::<Vec<_>>(),
        candidates.len()
    )
    .unwrap();
    write!(js, "\"verified_maps\":{verified_count},\"rejected_maps\":{rejected},\"distinct_permutations\":{},\"group_order\":{},\"candidate_set_equals_derived_group\":{closed},", compiled.len(), group.len()).unwrap();
    js.push_str("\"group\":[");
    for (e, g) in group.iter().enumerate() {
        if e > 0 {
            js.push(',');
        }
        let a = &compiled[g];
        write!(
            js,
            "{{\"element\":{e},\"source_for_target\":{g:?},\"loop_map\":{a:?}}}"
        )
        .unwrap();
    }
    js.push_str("],\"owners\":[");
    for (o, m) in owners.iter().enumerate() {
        let b = bits(m);
        let stab: Vec<usize> = (0..group.len())
            .filter(|&e| image(&group[e], &b) == *m)
            .collect();
        let others: BTreeSet<String> = group
            .iter()
            .map(|g| image(g, &b))
            .filter(|x| x != m && owner_set.contains(x.as_str()))
            .collect();
        if o > 0 {
            js.push(',');
        }
        write!(
            js,
            "{{\"mask\":\"{m}\",\"stabilizer\":{stab:?},\"other_owners_in_orbit\":{:?}}}",
            others.iter().collect::<Vec<_>>()
        )
        .unwrap();
    }
    let mut seen: BTreeSet<String> = BTreeSet::new();
    let mut orbits = 0usize;
    let route_set: BTreeSet<&str> = routes.iter().map(String::as_str).collect();
    let mut sizes: BTreeMap<usize, usize> = BTreeMap::new();
    for m in &routes {
        if seen.contains(m) {
            continue;
        }
        orbits += 1;
        let b = bits(m);
        let orbit: BTreeSet<String> = group.iter().map(|g| image(g, &b)).collect();
        let present = orbit
            .iter()
            .filter(|x| route_set.contains(x.as_str()))
            .count();
        *sizes.entry(present).or_default() += 1;
        seen.extend(orbit);
    }
    write!(js, "],\"route_masks\":{},\"route_mask_orbits_present\":{orbits},\"route_orbit_sizes_present\":{:?}}}", routes.len(), sizes.iter().map(|(k, v)| [*k, *v]).collect::<Vec<_>>()).unwrap();
    fs::write(&args[5], js).unwrap();
}
