//! A literal end-to-end RustRed workflow.
//!
//! The concrete massive tadpole is only input data for this example.  Every
//! IBP relation, tensor projector, denominator lowering, and reduction rule is
//! generated by the loop-count- and topology-neutral production APIs.

use std::collections::BTreeSet;

use rustred::*;
use symbolica::{atom::Atom, try_parse};

fn parse_atom(input: &str) -> Atom {
    try_parse!(input, default_namespace = "rustred_example").expect("valid Symbolica input")
}

fn integral<const N: usize>(powers: [i64; N]) -> ConcreteIntegralKey {
    ConcreteIntegralKey::try_new(powers).expect("nonempty integral-index vector")
}

fn main() {
    let coefficients = CoefficientContext::new(["d", "m2", "A", "B", "C"]);
    let family = IntegralFamily::new(
        "user-supplied-family",
        vec!["k".into()],
        Vec::new(),
        coefficients.clone(),
        coefficients.parameter("d").expect("declared d"),
        // D1 = k.k - m2 in the ordered scalar-product basis [k.k].
        vec![AffineDenominator::new(
            coefficients.parse("-m2").expect("valid mass"),
            vec![coefficients.one()],
        )],
        Vec::new(),
        vec![coefficients.zero()],
    )
    .expect("complete denominator basis");

    // This is the generic LiteRed-like derivation boundary: no concrete seed
    // powers or recurrence are supplied to the generator.  For L loops and E
    // external momenta RustRed generates all L*(L+E) ordinary IBPs and
    // E*(E-1)/2 LI relations.  A concrete target is supplied only later when
    // applying those generated parametric relations.
    let generator = ParametricIbpGenerator::try_new(&family).expect("IBP generator");
    let generated = generator.generate().expect("fully parametric IBPs");
    let parametric_context = generated.context().clone();

    let mut base_limits = GeneratedFamilyRuleSystemLimits::default();
    base_limits.discovery.adaptive.max_search_depth = 0;
    base_limits.live_leaf_queue.translation_radius = 0;
    base_limits.live_leaf_queue.max_translation_points = 1;
    let base = GeneratedFamilyRuleSystemCompiler::compile(
        &family,
        &parametric_context,
        SectorRestrictions::unrestricted(family.denominator_count())
            .expect("valid sector restrictions"),
        PowerShiftPolicy::FormalGeneric,
        IntegralOrderingPolicy::RustRedUnshiftedV1,
        GeneratedFamilyRuleSystemConfig::default(),
        base_limits,
    )
    .expect("generic sector/rule discovery");
    let fixed_point = GeneratedFamilyFixedPointCompiler::compile(
        &family,
        &parametric_context,
        base,
        GeneratedFamilyFixedPointConfig {
            base_search_depth: 0,
            maximum_rounds: 1,
            residual_frontier_depth: 1,
            residual_anchor_local_depth: 0,
            maximum_local_depth: 1,
            selection: GeneratedFamilyFixedPointSelectionPolicy::AllResidualSubsectorFirst,
            stop_on_no_strict_improvement: false,
        },
        GeneratedFamilyFixedPointLimits::default(),
    )
    .expect("residual fixed point");
    fixed_point
        .replay(&family, &parametric_context)
        .expect("certificate replay");

    // The only reduction policy supplied by the user is the terminal/master
    // choice.  RustRed never infers an uncovered integral to be a master.
    let master = integral([1]);
    let provider = GeneratedFamilyFixedPointProvider::try_with_selected(
        &family,
        &parametric_context,
        fixed_point,
        [master.clone()],
        GeneratedFamilyFixedPointProviderLimits::default(),
    )
    .expect("certified rule provider");
    provider.replay().expect("provider replay");

    let syntax = SymbolicaTensorSyntax::vakint().expect("valid tensor syntax");
    let tensor_compiler = SymbolicaTensorNumeratorCompiler::try_new(
        &family,
        syntax,
        [("k".to_owned(), parse_atom("vakint::k(3)"))],
        SymbolicaTensorNumeratorLimits::default(),
    )
    .expect("tensor compiler");

    let mu = "user_space::mink4(4,11)";
    let nu = "user_space::mink4(4,22)";
    let rho = "user_space::mink4(4,33)";
    let a = "user_space::mink4(4,41)";
    let b = "user_space::mink4(4,42)";
    let c = "user_space::mink4(4,43)";
    let e = "user_space::mink4(4,44)";
    let numerator = parse_atom(&format!(
        "rustred::A*vakint::k(3,{mu})*vakint::k(3,{nu})\
         +rustred::B*vakint::k(3,{rho})*vakint::p(1,{rho})\
         +rustred::C*vakint::k(3,{a})*vakint::k(3,{b})\
          *vakint::k(3,{c})*vakint::k(3,{e})"
    ));
    let compiled = tensor_compiler
        .compile(numerator.as_view())
        .expect("Symbolica tensor numerator");
    compiled
        .verify_replay(&tensor_compiler)
        .expect("numerator replay");

    let mut engine = ParametricReductionEngine::new(
        family.fingerprint(),
        family.coefficient_context(),
        IntegralOrderingPolicy::RustRedUnshiftedV1,
        provider,
        ReductionEngineLimits::default(),
    );
    let projection = compiled
        .project(&family, GenericTensorPolynomialLimits::default())
        .expect("native tensor projection");
    let lowering = projection
        .lower(&family, &integral([4]))
        .expect("scalar-product denominator lowering");
    let result = TensorParametricReductionComposer::new(&family)
        .reduce_authenticated_covariant_polynomial(lowering, &mut engine)
        .expect("IBP application");
    result.require_complete().expect("complete reduction");
    result.verify(&family).expect("local certificate replay");
    result
        .verify_with_engine(&family, &mut engine)
        .expect("engine/cache replay");

    println!(
        "family: loops={}, external={}, denominators={}",
        family.loop_count(),
        family.external_count(),
        family.denominator_count()
    );
    println!(
        "derived: ordinary_ibp={}, lorentz_invariance={}",
        generated.ordinary_ibp().len(),
        generated.lorentz_invariance().len()
    );
    println!("derived parametric rows (shift, coefficient):");
    for row in generated.ibp_li() {
        println!("  {:?}", row.row_id());
        for (shift, coefficient) in row.terms() {
            println!("    {:?}: {}", shift.values(), coefficient.to_expression());
        }
    }
    println!("input numerator: {numerator}");
    println!("input integral: J{:?}", integral([4]).powers());
    println!("selected master: J{:?}", master.powers());
    println!("certificate replay: ok");
    println!("complete reduction on the retained generic domain:");
    for (covariant, terms) in result.scalar_reduction().structures() {
        let rendered = compiled
            .render_covariant(covariant)
            .expect("rendered covariant");
        for (key, term) in terms {
            println!(
                "  {} * ({}) * J{:?}",
                rendered,
                term.coefficient().to_expression(),
                key.powers()
            );
        }
    }
    println!(
        "retained covariants={}, scalar guards={}, uncovered leaves={}",
        result.scalar_reduction().structures().len(),
        result.scalar_guards().len(),
        result.scalar_reduction().uncovered_leaves().len()
    );

    // `require_complete` means that no integral leaf is uncovered.  It does
    // not discard exceptional-domain information. Print the complete
    // inventory, grouping only identical rendered polynomials; mathematically
    // equivalent loci retain their distinct proof provenance in `result`.
    let mut required_nonzero = BTreeSet::new();
    for source_projection in result.projection().source_projections() {
        for condition in source_projection.domain().family().conditions() {
            required_nonzero.insert(condition.polynomial().to_expression().to_string());
        }
        for condition in source_projection.domain().projection_nonzero_conditions() {
            required_nonzero.insert(condition.polynomial().to_expression().to_string());
        }
    }
    for condition in result.projection().weight_nonzero_conditions() {
        required_nonzero.insert(condition.polynomial().to_expression().to_string());
    }
    for lowering in result.authenticated_lowering().lowerings().values() {
        for condition in lowering.domain().family().conditions() {
            required_nonzero.insert(condition.polynomial().to_expression().to_string());
        }
        for condition in lowering.domain().coefficient_nonzero_conditions() {
            required_nonzero.insert(condition.polynomial().to_expression().to_string());
        }
    }
    for guard in result.scalar_guards() {
        required_nonzero.insert(guard.condition().polynomial().to_expression().to_string());
    }
    for (_, conditions) in result.scalar_certified_domains() {
        for condition in conditions {
            required_nonzero.insert(condition.polynomial().to_expression().to_string());
        }
    }
    println!(
        "required nonzero polynomial inventory (exact-string grouping; origins retained in certificate):"
    );
    for polynomial in required_nonzero {
        println!("  {polynomial} != 0");
    }
}
