use crate::algebra::ExactAlgebraLimits;

/// Resource policy for exact evaluation, projection, and retention.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SymbolicaAffineDenominatorLimits {
    pub exact_algebra: ExactAlgebraLimits,
    pub max_input_bytes: usize,
    pub max_input_nodes: usize,
    pub max_nesting_depth: usize,
    pub max_label_bytes: usize,
    pub max_total_label_bytes: usize,
    pub max_base_parameters: usize,
    pub max_momenta: usize,
    pub max_combined_variables: usize,
    pub max_scalar_product_coordinates: usize,
    pub max_external_gram_entries: usize,
    pub max_external_gram_polynomial_terms: usize,
    pub max_external_gram_exponent_entries: usize,
    pub max_external_gram_integer_bits: usize,
    pub max_abs_power: u32,
    pub max_arithmetic_operations: u64,
    pub max_combined_polynomial_terms: usize,
    pub max_combined_exponent_entries: usize,
    pub max_coefficient_integer_bits: usize,
    pub max_combined_retained_bytes: usize,
    pub max_dense_degree_box_terms: usize,
    pub max_dense_degree_box_exponent_entries: usize,
    pub max_aggregate_dense_degree_box_terms: usize,
    pub max_aggregate_dense_degree_box_exponent_entries: usize,
    pub max_projection_groups: usize,
    pub max_projection_denominator_replication_terms: usize,
    pub max_projection_denominator_replication_exponent_entries: usize,
    pub max_projection_gram_operations: usize,
    pub max_projected_polynomial_terms: usize,
    pub max_projected_exponent_entries: usize,
    pub max_projected_integer_bits: usize,
    pub max_projected_retained_bytes: usize,
    pub max_normalized_expression_nodes: usize,
    pub max_normalized_expression_integer_bits: usize,
    pub max_normalized_expression_bytes: usize,
    pub max_compiled_retained_bytes: usize,
}

impl Default for SymbolicaAffineDenominatorLimits {
    fn default() -> Self {
        Self {
            exact_algebra: ExactAlgebraLimits {
                max_exponent: u16::MAX,
                max_polynomial_terms: 100_000,
                max_term_operations: 1_000_000,
            },
            max_input_bytes: 16 * 1024 * 1024,
            max_input_nodes: 100_000,
            max_nesting_depth: 256,
            max_label_bytes: 1_024,
            max_total_label_bytes: 1024 * 1024,
            max_base_parameters: 4_096,
            max_momenta: 1_024,
            max_combined_variables: 4_096,
            max_scalar_product_coordinates: 1_000_000,
            max_external_gram_entries: 1_000_000,
            max_external_gram_polynomial_terms: 4_000_000,
            max_external_gram_exponent_entries: 16_000_000,
            max_external_gram_integer_bits: 256_000_000,
            max_abs_power: 256,
            max_arithmetic_operations: 10_000_000,
            max_combined_polynomial_terms: 100_000,
            max_combined_exponent_entries: 8_000_000,
            max_coefficient_integer_bits: 64_000_000,
            max_combined_retained_bytes: 256 * 1024 * 1024,
            max_dense_degree_box_terms: 16_000_000,
            max_dense_degree_box_exponent_entries: 64_000_000,
            max_aggregate_dense_degree_box_terms: 100_000_000,
            max_aggregate_dense_degree_box_exponent_entries: 400_000_000,
            max_projection_groups: 100_000,
            max_projection_denominator_replication_terms: 16_000_000,
            max_projection_denominator_replication_exponent_entries: 64_000_000,
            max_projection_gram_operations: 1_000_000,
            max_projected_polynomial_terms: 4_000_000,
            max_projected_exponent_entries: 64_000_000,
            max_projected_integer_bits: 256_000_000,
            max_projected_retained_bytes: 512 * 1024 * 1024,
            max_normalized_expression_nodes: 4_000_000,
            max_normalized_expression_integer_bits: 64_000_000,
            max_normalized_expression_bytes: 64 * 1024 * 1024,
            max_compiled_retained_bytes: 1024 * 1024 * 1024,
        }
    }
}
