use std::collections::{BTreeMap, BTreeSet};
use std::sync::Arc;

use crate::family::IntegralKey;
use crate::sector::{ComplexityKey, OrderingPolicy};

use super::super::permutation::Verified;
use super::{
    Canonicalization, CanonicalizationLimits, DescendingCanonicalization, Error, ExactOrbit,
    OrbitImage, RoutingWitness,
};

/// Immutable owner of the finite group generated by authenticated internal
/// denominator permutations.
///
/// Input generators are consumed. Their exact group closure is derived,
/// deduplicated, bounded, and stored in lexicographic permutation order. The
/// identity is inserted by construction, so minimum-orbit canonicalization
/// can never make an integral harder.
#[derive(Debug)]
pub struct Canonicalizer {
    family_fingerprint: Arc<String>,
    ordering: OrderingPolicy,
    arity: usize,
    generator_count: usize,
    group: Box<[Arc<[usize]>]>,
    limits: CanonicalizationLimits,
}

impl Canonicalizer {
    pub fn try_new(
        ordering: OrderingPolicy,
        generators: impl IntoIterator<Item = Verified>,
        limits: CanonicalizationLimits,
    ) -> Result<Self, Error> {
        let mut retained = Vec::new();
        let mut expected_arity = None;
        let mut expected_family_fingerprint: Option<Arc<String>> = None;
        for (ordinal, generator) in generators.into_iter().enumerate() {
            let requested = ordinal.checked_add(1).ok_or(Error::ResourceCountOverflow {
                resource: "generator count",
            })?;
            check_limit("generator count", requested, limits.max_generators)?;
            let (family_fingerprint, entries) = generator.into_parts();
            if let Some(expected) = &expected_family_fingerprint {
                if expected.as_str() != family_fingerprint.as_str() {
                    return Err(Error::OrbitInvariant {
                        detail: "authenticated symmetry generators belong to different families",
                    });
                }
            } else {
                expected_family_fingerprint = Some(family_fingerprint);
            }
            let arity = entries.len();
            if let Some(expected) = expected_arity {
                if arity != expected {
                    return Err(Error::WrongGeneratorArity {
                        generator: ordinal,
                        expected,
                        actual: arity,
                    });
                }
            } else {
                expected_arity = Some(arity);
            }
            validate_generator(ordinal, &entries)?;
            retained
                .try_reserve(1)
                .map_err(|_| Error::AllocationFailure {
                    resource: "authenticated generators",
                    requested,
                })?;
            retained.push(Arc::<[usize]>::from(entries));
        }
        let arity = expected_arity.ok_or(Error::EmptyGenerators)?;
        let family_fingerprint = expected_family_fingerprint.ok_or(Error::EmptyGenerators)?;
        retained.sort_unstable();
        retained.dedup();
        let generator_count = retained.len();
        let group = derive_group(arity, &retained, limits)?;
        Ok(Self {
            family_fingerprint,
            ordering,
            arity,
            generator_count,
            group,
            limits,
        })
    }

    pub const fn ordering(&self) -> OrderingPolicy {
        self.ordering
    }

    pub(crate) fn family_fingerprint(&self) -> &str {
        self.family_fingerprint.as_str()
    }

    pub const fn arity(&self) -> usize {
        self.arity
    }

    /// Number of value-distinct authenticated generators after deterministic
    /// deduplication. The derived identity is not counted unless supplied.
    pub const fn generator_count(&self) -> usize {
        self.generator_count
    }

    pub fn group_order(&self) -> usize {
        self.group.len()
    }

    pub const fn limits(&self) -> CanonicalizationLimits {
        self.limits
    }

    /// Complete exact group in stable lexicographic permutation order.
    pub fn group_elements(
        &self,
    ) -> impl ExactSizeIterator<Item = &[usize]> + DoubleEndedIterator + '_ {
        self.group.iter().map(AsRef::as_ref)
    }

    /// Exact routes for every authenticated group element in stable group
    /// order.  This crate-private boundary is used by immutable owner-index
    /// installation; detached [`RoutingWitness`] values are never accepted as
    /// independent group-membership authority.
    pub(crate) fn routing_witnesses(
        &self,
    ) -> impl ExactSizeIterator<Item = RoutingWitness> + DoubleEndedIterator + '_ {
        self.group
            .iter()
            .enumerate()
            .map(|(group_element, source_for_target)| RoutingWitness {
                group_element,
                source_for_target: source_for_target.clone(),
            })
    }

    /// Rejoin one retained route to this exact authenticated finite group.
    /// Value transport alone cannot establish that provenance.
    pub(crate) fn authenticates_route(&self, route: &RoutingWitness) -> bool {
        self.group
            .get(route.group_element)
            .is_some_and(|mapping| mapping.as_ref() == route.source_for_target.as_ref())
    }

    #[cfg(test)]
    pub(crate) fn unauthenticated_route_for_test(&self) -> RoutingWitness {
        RoutingWitness {
            group_element: self.group.len(),
            source_for_target: self.group[0].clone(),
        }
    }

    /// Enumerate every value-distinct image and an exact least route to it.
    /// Images are returned in ascending persisted complexity order.
    pub fn orbit(&self, source: &IntegralKey) -> Result<ExactOrbit, Error> {
        self.check_key(source)?;
        let source_complexity = self.ordering.complexity_key(source.powers())?;
        let mut images: BTreeMap<ComplexityKey, OrbitImage> = BTreeMap::new();
        for (group_element, mapping) in self.group.iter().enumerate() {
            let integral = transport_key(mapping, source)?;
            let complexity = self.ordering.complexity_key(integral.powers())?;
            match images.entry(complexity.clone()) {
                std::collections::btree_map::Entry::Vacant(entry) => {
                    entry.insert(OrbitImage {
                        integral,
                        complexity,
                        route: RoutingWitness {
                            group_element,
                            source_for_target: mapping.clone(),
                        },
                        routing_multiplicity: 1,
                    });
                }
                std::collections::btree_map::Entry::Occupied(mut entry) => {
                    if entry.get().integral != integral {
                        return Err(Error::OrbitInvariant {
                            detail: "injective complexity keys collided for distinct images",
                        });
                    }
                    entry.get_mut().routing_multiplicity =
                        entry.get().routing_multiplicity.checked_add(1).ok_or(
                            Error::ResourceCountOverflow {
                                resource: "orbit routing multiplicity",
                            },
                        )?;
                }
            }
        }
        let image_count = images.len();
        let mut sorted = Vec::new();
        sorted
            .try_reserve_exact(image_count)
            .map_err(|_| Error::AllocationFailure {
                resource: "distinct orbit images",
                requested: image_count,
            })?;
        sorted.extend(images.into_values());
        if sorted.is_empty() {
            return Err(Error::OrbitInvariant {
                detail: "the derived group produced an empty orbit",
            });
        }
        let routing_count = sorted.iter().try_fold(0usize, |count, image| {
            count
                .checked_add(image.routing_multiplicity)
                .ok_or(Error::ResourceCountOverflow {
                    resource: "orbit routing count",
                })
        })?;
        if routing_count != self.group.len() {
            return Err(Error::OrbitInvariant {
                detail: "distinct-image routing multiplicities do not cover the group",
            });
        }
        Ok(ExactOrbit {
            source: source.clone(),
            source_complexity,
            images: sorted.into_boxed_slice(),
            group_order: self.group.len(),
        })
    }

    /// Select the minimum exact complexity key in the complete orbit.
    pub fn canonicalize(&self, source: &IntegralKey) -> Result<Canonicalization, Error> {
        Canonicalization::from_orbit(self.orbit(source)?)
    }

    /// Build the reducer-facing chain `parent > raw_child >= canonical_child`.
    /// The strict proof is deliberately checked against the raw rule child;
    /// symmetry routing happens only after that proof succeeds.
    pub fn canonicalize_descending_child(
        &self,
        parent: &IntegralKey,
        raw_child: &IntegralKey,
    ) -> Result<DescendingCanonicalization, Error> {
        self.check_key(parent)?;
        self.check_key(raw_child)?;
        let raw_descent = self
            .ordering
            .prove_strict_descent(parent.powers(), raw_child.powers())?;
        let child = self.canonicalize(raw_child)?;
        DescendingCanonicalization::new(raw_descent, child)
    }

    fn check_key(&self, key: &IntegralKey) -> Result<(), Error> {
        if key.powers().len() == self.arity {
            Ok(())
        } else {
            Err(Error::WrongKeyArity {
                expected: self.arity,
                actual: key.powers().len(),
            })
        }
    }
}

fn validate_generator(ordinal: usize, entries: &[usize]) -> Result<(), Error> {
    let arity = entries.len();
    let mut seen = Vec::new();
    seen.try_reserve_exact(arity)
        .map_err(|_| Error::AllocationFailure {
            resource: "generator bijection replay",
            requested: arity,
        })?;
    seen.resize(arity, false);
    for &source in entries {
        let Some(slot) = seen.get_mut(source) else {
            return Err(Error::InvalidGenerator {
                generator: ordinal,
                source,
                arity,
            });
        };
        if std::mem::replace(slot, true) {
            return Err(Error::DuplicateGeneratorSource {
                generator: ordinal,
                source,
            });
        }
    }
    Ok(())
}

fn derive_group(
    arity: usize,
    generators: &[Arc<[usize]>],
    limits: CanonicalizationLimits,
) -> Result<Box<[Arc<[usize]>]>, Error> {
    admit_group_size(1, arity, limits)?;
    let mut identity = Vec::new();
    identity
        .try_reserve_exact(arity)
        .map_err(|_| Error::AllocationFailure {
            resource: "identity permutation",
            requested: arity,
        })?;
    identity.extend(0..arity);
    let identity: Arc<[usize]> = identity.into();

    let mut known = BTreeSet::new();
    known.insert(identity.clone());
    let mut discovered = Vec::new();
    discovered
        .try_reserve(1)
        .map_err(|_| Error::AllocationFailure {
            resource: "derived group elements",
            requested: 1,
        })?;
    discovered.push(identity);

    let mut cursor = 0usize;
    while cursor < discovered.len() {
        let current = discovered[cursor].clone();
        for generator in generators {
            let composition = compose(&current, generator)?;
            if known.contains(composition.as_slice()) {
                continue;
            }
            let requested =
                discovered
                    .len()
                    .checked_add(1)
                    .ok_or(Error::ResourceCountOverflow {
                        resource: "group order",
                    })?;
            admit_group_size(requested, arity, limits)?;
            let composition: Arc<[usize]> = composition.into();
            if known.insert(composition.clone()) {
                discovered
                    .try_reserve(1)
                    .map_err(|_| Error::AllocationFailure {
                        resource: "derived group elements",
                        requested,
                    })?;
                discovered.push(composition);
            }
        }
        cursor += 1;
    }

    discovered.sort_unstable();
    Ok(discovered.into_boxed_slice())
}

/// If `left` is applied first and `right` second, target `j` ultimately reads
/// source `left[right[j]]`.
fn compose(left: &[usize], right: &[usize]) -> Result<Vec<usize>, Error> {
    let mut composition = Vec::new();
    composition
        .try_reserve_exact(left.len())
        .map_err(|_| Error::AllocationFailure {
            resource: "composed permutation",
            requested: left.len(),
        })?;
    composition.extend(right.iter().map(|&slot| left[slot]));
    Ok(composition)
}

fn transport_key(mapping: &[usize], source: &IntegralKey) -> Result<IntegralKey, Error> {
    let mut target = Vec::new();
    target
        .try_reserve_exact(mapping.len())
        .map_err(|_| Error::AllocationFailure {
            resource: "transported integral powers",
            requested: mapping.len(),
        })?;
    target.extend(
        mapping
            .iter()
            .map(|&source_slot| source.powers()[source_slot]),
    );
    Ok(IntegralKey::try_from_preallocated(target)?)
}

fn admit_group_size(
    order: usize,
    arity: usize,
    limits: CanonicalizationLimits,
) -> Result<(), Error> {
    check_limit("group order", order, limits.max_group_order)?;
    let entries = order
        .checked_mul(arity)
        .ok_or(Error::ResourceCountOverflow {
            resource: "group entries",
        })?;
    check_limit("group entries", entries, limits.max_group_entries)
}

fn check_limit(resource: &'static str, requested: usize, limit: usize) -> Result<(), Error> {
    if requested > limit {
        Err(Error::ResourceLimit {
            resource,
            requested,
            limit,
        })
    } else {
        Ok(())
    }
}
